function _precompile_()
    ccall(:jl_generating_output, Cint, ()) == 1 || return nothing
    # precompile(Tuple{SIMDPirates.var"##s40#188",Any,Any,Any})
    # precompile(Tuple{SIMDPirates.var"##s40#145",Any,Any,Any})
    # precompile(Tuple{SIMDPirates.var"##s14#55",Any,Any,Any,Any,Any,Any,Any,Any})
    # precompile(Tuple{SIMDPirates.var"##s30#88",Any,Any,Any,Any,Any,Any})
    # precompile(Tuple{SIMDPirates.var"##s30#65",Any,Any,Any,Any,Any,Any,Any})
    # precompile(Tuple{SIMDPirates.var"##s15#61",Any,Any,Any,Any,Any,Any,Any})
    # precompile(Tuple{SIMDPirates.var"##s30#119",Any,Any,Any,Any,Any,Type,Any,Any,Any})
    # precompile(Tuple{SIMDPirates.var"##s40#122",Any,Any,Any,Any,Any,Any,Any,Any,Any})
    precompile(Tuple{typeof(SIMDPirates.llvmconst),Int64,Type,Float64})
    precompile(Tuple{typeof(SIMDPirates.llvmconst),Int64,Type,Int64})
    precompile(Tuple{typeof(SIMDPirates.subvector),String,Int64,String,String,Int64,Int64})
    precompile(Tuple{typeof(SIMDPirates.scalar2vector),String,Int64,String,String})
#     precompile(Tuple{SIMDPirates.var"##s30#67",Any,Any,Any,Any,Any,Any,Any,Any})
#     precompile(Tuple{SIMDPirates.var"##s40#120",Any,Any,Any,Any,Any,Any,Any,Type,Any})
#     precompile(Tuple{SIMDPirates.var"##s29#60",Any,Any,Any,Any,Any,Any,Any,Any})
#     precompile(Tuple{SIMDPirates.var"##s40#136",Any,Any,Any})
#     precompile(Tuple{SIMDPirates.var"##s30#83",Any,Any,Any,Any,Any})
#     precompile(Tuple{SIMDPirates.var"##s40#134",Any,Any,Any,Any,Any})
#     precompile(Tuple{SIMDPirates.var"##s18#53",Any,Any,Any,Any,Any,Any,Any})
#     precompile(Tuple{SIMDPirates.var"##s15#116",Any,Any,Any,Any,Any,Any,Any})
end
